config/routes.rb
Rails.application.routes.draw do
  resources :programs do
    post 'execute'
  end

   root 'programs#index'

end

app/models/program.rb
class Program < ActiveRecord::Base
  validates :code,:title, presence: true
  validates :title, uniqueness: true
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:update, :destroy]
  def execute

    ApplicationHelper.execute(Program.find(params[:program_id]))

    @programs = Program.all
    @active = params[:program_id]
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
  
  def index
    
    @programs = Program.all
    @program = Program.new
  end

  # POST /programs
  # POST /programs.json
  def create
    Program.all.each do |p|
      if p.title == program_params[:title]
        @program = p
      end
    end
 if @program.nil?
   
        @program = Program.new(program_params)
        if @program.save
          ApplicationHelper.execute(@program)
        end
      else
        if @program.update(program_params)
          ApplicationHelper.execute(@program)
        end
      end
    @active = @program.id

    respond_to do |format|
     
      @programs = Program.all
      format.js
    end
  end

  def edit
    @program = Program.find(params[:id])
    puts @program.code
     @active = @program.id
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
      # format.html { redirect_to :back}

      else
      #  format.html { redirect_to :back}
      end
      execute
      @programs = Program.all
      format.js
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    @programs = Program.all
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_program
    @program = Program.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def program_params
    params.require(:program).permit(:title, :code, :failed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'yaml'
  
  def self.clamp min, max,val
    [[val, max].min, min].max
  end
  
  def self.color(r,g,b)
    arr = [r,g,b]
    arr[0]= clamp(0,255,arr[0])
    arr[1]= clamp(0,255,arr[1])
    arr[2]= clamp(0,255,arr[2])
    File.open("color",'w'){|file| file.puts(YAML.dump(arr))}
  end
  
  def self.colorarray(a)
    a[0]= clamp(0,255,a[0])
    a[1]= clamp(0,255,a[1])
    a[2]= clamp(0,255,a[2])
     File.open("color",'w'){|file| file.puts(YAML.dump(a))}
  end
  
  #this is a clusterfuck, do not attemt to understand this
  def self.execute(program)
    # byebug
    program.failed = nil

    ActiveRecord::Base.connection.close
    Status.new().save if Status.first.nil? 
    
    Thread.list.each do |thread|
      
        thread.exit if thread.to_s == Status.first.thread
        
    end
    
   thread = Thread.new do
      begin
        eval(program.code)
      rescue Exception => e
      program.failed = e.to_s
      end
    end
    Status.first.destroy
    status = Status.new
    status.thread  = thread.to_s
     status.save

    sleep(0.1)
    program.save
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Led3k" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/programs/_form.html.erb
<h4>Create/Edit a Program</h4>
<%= form_for(@program,remote: true) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
  	<label>Name</label>
    <%= f.text_field :title, placeholder: 'Title', style: 'width:100%' %>
  </div>

  
  <div class="field">
  	<label>Ruby Code</label>
    <%= f.text_area :code, placeholder: 'Ruby code for controlling the Leds, functions: color(r,g,b), colorarray([r,g,b])',style: 'height: 400px; width:100%' %>
  </div>
    <div class="actions">
    <%= f.submit 'Run/Save',style: 'width:150px',class:'button'%>
  </div>
<% end %>

app/views/programs/_program.html.erb
<%css= 'secondary'%>
<%css = 'success' if @active.to_i == program.id %>
<td><%=link_to(program.title, program_execute_path(program.id),method: :post,class:'button '+css,remote: true)%>
<%=link_to('edit', edit_program_path(program.id),class:'button warning',remote: true)%>
<%=link_to('delete', program_path(program.id),method: :delete,class:'button alert',remote: true)%></td>

<td>Errors: <%=program.failed%></td>

app/views/programs/_programs.html.erb
<div  id='programs'>
<h4>Run Programs</h4>
<table class='stack'>

	<%@programs.each do |program|%>
	<tr>
<%=render program%>
</tr>
<%end%>
</table>
</div>

app/views/programs/create.js.erb
$('#programs').replaceWith("<%= escape_javascript(render 'programs')%>");

app/views/programs/destroy.js.erb
$('#programs').replaceWith("<%= escape_javascript(render 'programs')%>");

app/views/programs/edit.js.erb
var elem = document.createElement('textarea');
elem.innerHTML = "<%=@program.code.dump[1..-2]%>";
$('#program_code').val(elem.value);
elem.innerHTML = "<%=@program.title.dump[1..-2]%>";
$('#program_title').val(elem.value);

app/views/programs/execute.js.erb
$('#programs').replaceWith("<%= escape_javascript(render 'programs')%>");

app/views/programs/index.html.erb
<div class='row'>
	<div class='column'>
		<%=render 'programs'%>
</div>
<div class='column'>
<%=render 'form'%>
</div>
</div>